
title: AIN212 Elements of Data Science
author:
  name: Nazli Ikizler Cinbis
description: Web page for AIN212 Elements of Data Science course in Hacettepe University.
show_excerpts: false # set to true to show excerpts on the homepage
theme: minima
