
title: AIN212 Elements of Data Science
description: Web page for AIN212 Elements of Data Science course in Hacettepe University
show_excerpts: true # set to true to show excerpts on the homepage
theme: minima
